#!/usr/bin/env bash
# supress output helper script to launch inotifywait optional logging   09/15/2025 01/13/2026
#nohup /usr/local/recentchanges/inotify "$@" > /dev/null 2>&1 &
SCRIPT_PATH="$( dirname "$0")"
fmt="%Y-%m-%d %H:%M:%S"
log_date=$(date +"$fmt")
echo $log_date > /tmp/inotify.log
nohup "$SCRIPT_PATH"/inotify "$@" >> /tmp/inotify.log 2>&1 &
echo $! > /tmp/inotify_watcher.pid
