#!/usr/bin/env bash
get_vrn(){
if [ "$1" = "-v" ]; then
   echo "version 5.0 h&k enterprisez 01/15/2026"
   echo
   echo "recentchanges aka Developer buddy"
   echo
   exit
elif [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ] ; then
   echo "version 5.0"
   echo
   echo "recentchanges aka Developer buddy"
   echo
   echo "Makes an xzm of all changes 5 minutes or newer. A manifest will be included as well as a pull transfer"
   echo "log. These will be sent to /tmp as rntchanges.xzm ect"
   echo
   echo "Useful if you compiled a program you can ie specify recent changes 5 to pull all new files 5 seconds"
   echo "or newer"
   echo
   echo "Modes available Search or SRC or Query See bottom after usage how to use modes"
   echo
   echo
   echo "recentchanges s         where s is time in seconds"
   echo
   echo -e "usage:    recentchanges \t\t grab all files 5 minutes or new		these will include system search as well"
   echo -e "usage:    recentchanges 30	\t grab all files 30 seconds or newer"
   echo
   echo
   echo "Modes"
   echo
   echo "Search        for just a system search"
   echo
   printf "recentchanges search \t search for files 5 minutes or newer\n"
   printf "recentchanges search 30 \t search for files 30 seconds or newer\n"
   echo
   echo "Search for files newer than a file or directory"
   echo
   echo "recentchanges search /home/guest/myfile.txt    search for files newer than myfile"
   echo "recentchanges search myfile.txt"
   echo "recentchanges search /home/guest/My\ Directory\ two/with\ spaces/   ... newer than directory"
   echo
   echo
   echo "SRC"
   echo
   printf "recentchanges SRC \t\t  Target a root directory. Useful if you compiled an application.\n\n"
   echo     " examples:"
   echo     " recentchanges SRC, recentchanges 60 SRC or recentchanges SRC 180"
   echo
   echo
   echo " This feature will package an application with a customized name into an .xzm"
   echo " It allows to focus the search and exclude even files that made it past the filter."
   echo " This was the main intent of the concept of recentchanges and everything is fully automatic"
   echo
   echo " Note: when using this feature ensure that you know there is a parent directory with files in it"
   echo " as well its most useful within a definite period of time. The fact that a large amount of files went"
   echo " to one directory allows this to be possible. If for some reason it doesnt work use recentchanges to make rntfiles.xzm"
   echo
   echo "Query"
   echo
   echo "Find out information about files from searches."
   echo
   echo "Inverse the search with Symlink"
   echo
   printf "rnt \t\t\t shortcut for recentchanges doesnt inverse\t output /tmp\n"
   echo "rnt n"
   printf "rnt search \t\t search for filtered rather than unfiltered files\t output /Downloads\n"
   printf "rnt search 30 \t\t search for filtered files 30 seconds or newer\n"
   printf "rnt search myfile.txt \t search for unfiltered rather than filtered files newer than myfile\n"
   echo
   echo
   echo "If having problems with keys."
   echo "1. Try to delete the all .gpg to make new ones. 2. Failing that do the same as 1 but change email in config.toml to make a new keypair"
   echo 
   echo "or option 3."
   echo "delete the keys for user and root"
   echo "gpg --list-keys . grab the key fingerprint for the email in config.toml."
   echo "as user gpg --delete-sercet-keys <fingerprint>"
   echo "gpg --delete-keys <fingerprint>"
   echo "then as root. sudo su"
   echo "gpg --delete-sercret-keys <fingerprint>"
   echo "gpg --delete-keys <fingerprint>"
   echo
   echo "failing that use \`recentchanges reset\` for instructions and or to delete the key pair and reset"
   exit
fi
exit 1
}
if [ "$1" = "-h" ]; then get_vrn $1 ; fi

