#!/usr/bin/env python3
# run set tasks for recentchanges qt gui
import sys
from src.dirwalker import main_entry as dirwalker_main
from src.findfile import main_entry as findfile_main
from src.recentchangessearch import main as recentchanges_main
from src.recentchangessearchparser import build_subparser
from src.gpgkeymanagement import import_key
from src.qtfunctions import load_konsole
from src.qtfunctions import load_file_manager
from src.qtfunctions import kill_process

# 02/02/2026


def main(argv):
    arglen = len(argv)
    if not argv or arglen < 3:
        print("Insufficient args")
        return 1
    script = argv[1].lower()
    args = argv[2:]
    cmd = args[0]
    if arglen > 5:

        DISPATCH_MAP = {
            "dirwalker.py": {
                "hardlink": 9,
                "scan": 6,
                "build": 5,
                "downloads": 10,
            },
            "recentchangessearch.py": recentchanges_main,
            "findfile.py": findfile_main,
            "import": import_key
        }

        entry = DISPATCH_MAP.get(script)
        # os.setsid()
        # p_id = os.getpgid(0)
        # print("pid",  p_id)
        if isinstance(entry, dict):
            if cmd not in entry:
                print(
                    f"Invalid parameter for dirwalker; expected one of: "
                    f"{'/'.join(entry.keys())}, got {cmd}"
                )
                return 1
            min_args = entry[cmd]
            if len(args) < min_args:
                print(f"Not enough args for '{cmd}', expected {min_args}, got {len(args)}")
                return 1

            return dirwalker_main(args)

        elif entry:

            if script == "recentchangessearch.py":
                recent_args = build_subparser(script)
                return entry(*recent_args)
            elif script == "findfile.py":
                return entry(args)
            elif script == "import":
                return entry(args)
    else:
        if script == "run":
            if cmd == "filemanager":
                return load_file_manager(*args[1:])  # lclhome, popPATH=
            if cmd == "terminal":
                return load_konsole(*args[1:])  # lclhome, popPATH=
            if cmd == "kill":
                return kill_process(*args[1:])

    return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv))
